-- 创建数据库
CREATE DATABASE IF NOT EXISTS `user` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `problem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `record` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 创建远程访问用户
CREATE USER IF NOT EXISTS 'ygoj'@'%' IDENTIFIED BY 'ygoj123456';
GRANT ALL PRIVILEGES ON `user`.* TO 'ygoj'@'%';
GRANT ALL PRIVILEGES ON `problem`.* TO 'ygoj'@'%';
GRANT ALL PRIVILEGES ON `record`.* TO 'ygoj'@'%';
FLUSH PRIVILEGES;