spring:
    application:
        name: fileSystem
    cloud:
        nacos:
            server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
            config:
                import-check:
                    enabled: false
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 200MB

# 文件存储根目录
filesystem:
    root:
        path: file

server:
    port: 9201
