spring:
    application:
        name: gateway
    profiles:
        include: route
    cloud:
        nacos:
            server-addr: 127.0.0.1:8848
    data:
        redis:
            host: localhost
            port: 6379
            database: 0
server:
    port: 80
