spring:
    application:
        name: gateway
    profiles:
        include: route
    cloud:
        nacos:
            server-addr: 192.168.61.135:8848
    data:
        redis:
            host: 192.168.61.135
            port: 6379
            database: 0
server:
    port: 80
