spring:
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowed-origin-patterns: '*'
                        allowed-headers: '*'
                        allowed-methods: '*'
            routes:
                - id: record-route
                  uri: lb://service-record
                  predicates:
                    - Path=/api/record/**
                - id: user-route
                  uri: lb://service-user
                  predicates:
                      - Path=/api/user/**
                - id: problem-route
                  uri: lb://service-problem
                  predicates:
                      - Path=/api/problem/**
                - id: contest-route
                  uri: lb://service-problem
                  predicates:
                      - Path=/api/contest/**
                - id: problemset-route
                  uri: lb://service-problem
                  predicates:
                      - Path=/api/problemset/**
                - id: discuss-route
                  uri: lb://service-discuss
                  predicates:
                      - Path=/api/discuss/**
            default-filters:
                - StripPrefix=1