spring:
    application:
        name: service-user
    cloud:
        nacos:
            server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
            config:
                import-check:
                    enabled: false
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/user?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:123456}
        driver-class-name: com.mysql.cj.jdbc.Driver
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            database: ${REDIS_DATABASE:0}
server:
    port: 8001