spring:
    application:
        name: service-record
    cloud:
        nacos:
            server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
    config:
        import: "nacos:service-record.yaml"
    profiles:
        include:
            - feign
            - language
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/record?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:123456}
        driver-class-name: com.mysql.cj.jdbc.Driver
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        virtual-host: ${RABBITMQ_VIRTUAL_HOST:/judgeQueue}
        username: ${RABBITMQ_USERNAME:root}
        password: ${RABBITMQ_PASSWORD:root}

server:
    port: 8002

logging:
    level:
      com.ygoj.record.feign: debug
