feign:
    sentinel:
        enabled: true
spring:
    cloud:
        sentinel:
            transport:
                dashboard: 192.168.61.135:8858
            eager: true
            web-context-unify: false