spring:
    application:
        name: service-discuss
    cloud:
        nacos:
            server-addr: 192.168.61.135:8848
            config:
                import-check:
                    enabled: false
    datasource:
        url: jdbc:mysql://192.168.61.135:3306/discuss?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    data:
        redis:
            host: 192.168.61.135
            port: 6379
            database: 0
server:
    port: 8004
