spring:
    application:
        name: service-judger
    cloud:
        nacos:
            server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
            config:
                import-check:
                    enabled: false
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/problem?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:123456}
        driver-class-name: com.mysql.cj.jdbc.Driver
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        virtual-host: ${RABBITMQ_VIRTUAL_HOST:/judgeQueue}
        username: ${RABBITMQ_USERNAME:root}
        password: ${RABBITMQ_PASSWORD:root}
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            database: ${REDIS_DATABASE:0}
server:
    port: 8003

logging:
    level:
        com.alibaba.nacos: DEBUG